### PR TITLE
Enhance image uploader widget

### PR DESCRIPTION
**Pull request by vitorflg**
#### What problem is this solving?

- Drag and drop not working when an image is already selected
- Performance improvements to load image previews

#### How should this be manually tested?

[Workspace](https://vitorflg--storecomponents.myvtex.com/admin/cms/site-editor)

#### Type of changes

| ✔️  | Type of Change                                                                            |
| --- | ----------------------------------------------------------------------------------------- |
| ✔️  | Bug fix                                |
| \_  | New feature                        |
| \_  | Breaking change  |
| \_  | Technical improvements  |

### CODE REVIEW

**Review by davicosta99 — CHANGES_REQUESTED** [review]
- What's the size you're asking File manager for the images? We need to ask for three times (@3x) the size that the image will be shown, so the images look good on retina displays. Example: if the image will be displayed with a height of 100px, we need to ask for it with 300px of height.
- Can we show the placeholder state any time the user is hovering a file over the widget?

**Comment by vitorflg** [comment]
> * What's the size you're asking File manager for the images? We need to ask for three times (@3x) the size that the image will be shown, so the images look good on retina displays. Example: if the image will be displayed with a height of 100px, we need to ask for it with 300px of height.
> * Can we show the placeholder state any time the user is hovering a file over the widget?

1) Good to know! It was 2x, I`ve just updated!
2) Yes, I will do it!

**Comment by davicosta99** [comment]
Two comments about the hover behavior:
- The outline should be reduced 8px to the left and 8px to the right, but right now it's reducing more.
- There's this weird behavior when the mouse is resting in a certain region:
Gravação de Tela 2021-07-22 às 11 36 41

**Comment by vitorflg** [comment]
How are you measuring the outline gap?

Here is indicating 8px for each side:

Screen Shot 2021-07-22 at 1 52 28 PM

**Review by davicosta99 — APPROVED** [review]
LGTM

**Review by mateuspontes — APPROVED** [review]
this hover effect is weird, btw 😆

**Pull request merged**
