### PR TITLE
Add ColorPicker Widget

### PR DESCRIPTION
**Pull request by pmartin-webimpacto**
#### What problem is this solving?

Add a new Color Picker Widget to page editor. 

#### How should this be manually tested?

https://reviews--webimpacto.myvtex.com/admin/cms/site-editor/test-producto-soap/p

In the second row, admin/editor.rating.title component configuration. 

#### Screenshots or example usage

image

#### Type of changes

|       | Type of Change                                                                            |
| --- | ----------------------------------------------------------------------------------------- |
| \_  | Bug fix                                |
| ✔️  | New feature                        |
| \_  | Breaking change  |
| \_  | Technical improvements  |

### CODE REVIEW

**Comment by pmartin-webimpacto** [comment]
I can't change the  bot comment to select the proper options. 

It's a Minor Version (cause it add a new feature)

And there's nothing new to document, cause there isn't any doc about widgets :( 

Regards.

**Comment by thiagomurakami** [comment]
Hey @pmartin-webimpacto, thanks for contributing 😄 

I'd like to know why our style editor solution didn't work out for your case because by adding this widget, we're encouraging developers to put a color property in their components. While this is extremely useful, it may backfire if users needs to enter all their pages to customize a color.

**Comment by pmartin-webimpacto** [comment]
> Hey @pmartin-webimpacto, thanks for contributing 😄
> 
> I'd like to know why our style editor solution didn't work out for your case because by adding this widget, we're encouraging developers to put a color property in their components. While this is extremely useful, it may backfire if users needs to enter all their pages to customize a color.

Hi @thiagomurakami.  

The style editor on admin-pages works fine, and also the style builder for store theme. 

But in our case, we have a client/user that want one specific color for specific texts or backgrounds en their components and we can't associate it with any color schema,  for the moment our solution is a simple string input for put the color required. 

I know maybe we are encouraging devolopers to put a color property... but if we haven't this, maybe developers always select the 'Primary color'  and user don't want change the primary color for all the components and only this one.. :)

**Comment by thiagomurakami** [comment]
> [...] we have a client/user that want one specific color for specific texts or backgrounds en their components
>  [...] but if we haven't this, maybe developers always select the 'Primary color' and user don't want change the primary color for all the components and only this one.. :)

The [`design tokens`](https://styleguide.vtex.com/#/Introduction/Designing) solution won't solve *every* use case, just like you said, the client doesn't want to change the primary color for the whole store just to change the color of a single text + background. 

However, feedback and "real world" use cases are great not only to evolve the solution we currently have but also to have better and richer examples of _when_ and _why_ you should use this widget (when we properly document this stuff 😛).

Personally, it does seem to make sense to have this. I'll align with the other team members and give you a definite answer.

**Comment by felippenardi** [comment]
At this time we believe allowing the color pick as an editor option is moving the Site Editor to a direction that we don't envision in the product.

I really appreciate your time and effort in this contribution, but we'll have to decline it.

**Pull request closed without merging**
