### PR TITLE
Add bulgarian and pseudo language

### PR DESCRIPTION
**Pull request by camilavcoutinho**
Add pseudo language in order to implement In Context, a translation tool that gives the translators more context, making it possible for them to translate in a test environment.

### CODE REVIEW

**Review by marcelovicentegc — APPROVED** [review]
LGTM

**Comment by marcelovicentegc** [comment]
@camilavcoutinho, are we still good to go?
@vitorflg, did you have the chance to take a look at this?

**Comment by camilavcoutinho** [comment]
> @camilavcoutinho, are we still good to go?
> @vitorflg, did you have the chance to take a look at this?

@marcelovicentegc we are proofreading Bulgarian right now, so if you could wait a little bit to merge I would appreciate 😄

**Comment by camilavcoutinho** [comment]
@marcelovicentegc we are good to go 😄 . Could you give us a hand with the merge and deploy ?

**Comment by marcelovicentegc** [comment]
> @marcelovicentegc we are good to go 😄 . Could you give us a hand with the merge and deploy ?

Absolutely @camilavcoutinho ! Let's just hold this for tomorrow (messaged you why)

**Pull request merged**
